name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.production.AWS_PRIVATE_KEY }}

      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.production.AWS_PRIVATE_KEY }}
          script: |
            if [ ! -d codeex-quiz ]; then
              mkdir codeex-quiz
            fi

            cd codeex-quiz
            if [ ! -d codeex-quiz-server ]; then
              git clone https://github.com/cs-fedy/codeex-quiz-server.git
            fi

            cd codeex-quiz-server
            git fetch origin main
      - name: Start docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.production.AWS_PRIVATE_KEY }}
          script: |
            cd /path/to/project
            sudo docker-compose up -d
